// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYskF4rPT4OSWIkjrp6zHvX8ziAQeexUs',
    appId: '1:683739377184:web:670ad1f050f7ab09a15645',
    messagingSenderId: '683739377184',
    projectId: 'chat-app-cc926',
    authDomain: 'chat-app-cc926.firebaseapp.com',
    storageBucket: 'chat-app-cc926.firebasestorage.app',
    measurementId: 'G-8V10R3J1XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt0dgTUQldHL-rE7vhxUdZAQjEzrcNwxM',
    appId: '1:683739377184:android:fbb4c8126aea12bba15645',
    messagingSenderId: '683739377184',
    projectId: 'chat-app-cc926',
    storageBucket: 'chat-app-cc926.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUf2gXAYcs3CGIvo8WPtuFqf42o5fg8BQ',
    appId: '1:683739377184:ios:81d63bb9ea7d8a71a15645',
    messagingSenderId: '683739377184',
    projectId: 'chat-app-cc926',
    storageBucket: 'chat-app-cc926.firebasestorage.app',
    iosBundleId: 'com.example.akChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUf2gXAYcs3CGIvo8WPtuFqf42o5fg8BQ',
    appId: '1:683739377184:ios:81d63bb9ea7d8a71a15645',
    messagingSenderId: '683739377184',
    projectId: 'chat-app-cc926',
    storageBucket: 'chat-app-cc926.firebasestorage.app',
    iosBundleId: 'com.example.akChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYskF4rPT4OSWIkjrp6zHvX8ziAQeexUs',
    appId: '1:683739377184:web:6d3491e128e8baf9a15645',
    messagingSenderId: '683739377184',
    projectId: 'chat-app-cc926',
    authDomain: 'chat-app-cc926.firebaseapp.com',
    storageBucket: 'chat-app-cc926.firebasestorage.app',
    measurementId: 'G-ZVB8EC8ZWT',
  );
}
